const { SerialPort, ReadlineParser } = require('serialport')
const port = new SerialPort({ path:"COM6", baudRate:9600 })
const parser = new ReadlineParser()
port.pipe(parser)
parser.on('data', console.log)
